// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe0ohaviNrXMYgc6ChItlxN8hDeSwo9lU',
    appId: '1:450496617590:web:fd52cbb60be3ab57039357',
    messagingSenderId: '450496617590',
    projectId: 'complaints-application-85be3',
    authDomain: 'complaints-application-85be3.firebaseapp.com',
    storageBucket: 'complaints-application-85be3.firebasestorage.app',
    measurementId: 'G-PC2BNFDRN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FvkbnTS6-ZUBq-hSR5nsBW3PSXTZxhU',
    appId: '1:450496617590:android:4a27484c121b9df3039357',
    messagingSenderId: '450496617590',
    projectId: 'complaints-application-85be3',
    storageBucket: 'complaints-application-85be3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Lo0-xZGrb2Osv8oqbitgE1uMmHbuxRw',
    appId: '1:450496617590:ios:1c4b4f65c5129772039357',
    messagingSenderId: '450496617590',
    projectId: 'complaints-application-85be3',
    storageBucket: 'complaints-application-85be3.firebasestorage.app',
    iosBundleId: 'com.example.complaintsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Lo0-xZGrb2Osv8oqbitgE1uMmHbuxRw',
    appId: '1:450496617590:ios:1c4b4f65c5129772039357',
    messagingSenderId: '450496617590',
    projectId: 'complaints-application-85be3',
    storageBucket: 'complaints-application-85be3.firebasestorage.app',
    iosBundleId: 'com.example.complaintsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe0ohaviNrXMYgc6ChItlxN8hDeSwo9lU',
    appId: '1:450496617590:web:cc026ef87822a71f039357',
    messagingSenderId: '450496617590',
    projectId: 'complaints-application-85be3',
    authDomain: 'complaints-application-85be3.firebaseapp.com',
    storageBucket: 'complaints-application-85be3.firebasestorage.app',
    measurementId: 'G-XV46TTFVW6',
  );
}
